# Generated by Django 2.1.5 on 2019-01-13 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=15, unique=True)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('location_backups', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ID_connection_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ID_production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='devices',
            name='connection_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editordb.ID_connection_type'),
        ),
        migrations.AddField(
            model_name='devices',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editordb.ID_production'),
        ),
    ]
