# Generated by Django 2.1.5 on 2019-01-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editordb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='login',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='devices',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='id_connection_type',
            name='connection_type',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='id_production',
            name='production',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
