# Generated by Django 2.1.5 on 2019-01-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editordb', '0002_auto_20190115_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='location_backups',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
