# Generated by Django 2.1.5 on 2019-01-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editordb', '0003_auto_20190115_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crontab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InfoCrontab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('days', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='crontab',
            name='days',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days2days', to='editordb.InfoCrontab'),
        ),
        migrations.AddField(
            model_name='crontab',
            name='hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours2hours', to='editordb.InfoCrontab'),
        ),
        migrations.AddField(
            model_name='crontab',
            name='minutes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes2minutes', to='editordb.InfoCrontab'),
        ),
    ]
