# Generated by Django 2.1.5 on 2019-01-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editordb', '0005_auto_20190123_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='hours',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='minutes',
            field=models.CharField(max_length=2),
        ),
    ]
