# Generated by Django 2.1.5 on 2019-01-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editordb', '0008_auto_20190124_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontab',
            name='days',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='crontab',
            name='hours',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='crontab',
            name='minutes',
            field=models.CharField(max_length=2),
        ),
        migrations.DeleteModel(
            name='Days',
        ),
        migrations.DeleteModel(
            name='Hours',
        ),
        migrations.DeleteModel(
            name='Minutes',
        ),
    ]
