# Generated by Django 2.1.5 on 2019-01-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editordb', '0009_auto_20190124_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crontab',
        ),
    ]
