# Generated by Django 2.1.5 on 2019-01-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editordb', '0010_delete_crontab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crontab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='crontab',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editordb.Days'),
        ),
        migrations.AddField(
            model_name='crontab',
            name='hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editordb.Hours'),
        ),
        migrations.AddField(
            model_name='crontab',
            name='minute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editordb.Minutes'),
        ),
    ]
