# Generated by Django 2.1.5 on 2019-01-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editordb', '0011_auto_20190124_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='days',
            field=models.CharField(default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='hours',
            name='hours',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='minutes',
            field=models.IntegerField(default=None),
        ),
    ]
