# Generated by Django 2.1.5 on 2019-02-01 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editordb', '0013_auto_20190124_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='days',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='devices',
            name='ip_address',
            field=models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.validate_ipv4_address]),
        ),
    ]
