# Generated by Django 2.1.5 on 2019-02-15 16:21

import django.core.validators
from django.db import migrations, models
import editordb.models


class Migration(migrations.Migration):

    dependencies = [
        ('editordb', '0015_auto_20190212_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontab',
            name='day',
            field=models.CharField(max_length=3, unique=True, validators=[editordb.models.validate_day]),
        ),
        migrations.AlterField(
            model_name='crontab',
            name='hour',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='crontab',
            name='minute',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
    ]
